name = "worker"
type = "javascript"
zone_id = ""
account_id = "35dd2f2c2aa3d3e889c79d2f031cfe35"
route = ""
workers_dev = true
compatibility_date = "2022-02-04"
kv_namespaces = [ 
  { binding = "MOCKA_STORE", id = "5fd3210244ee4301b1422cf4f7278aa1", preview_id = "5fd3210244ee4301b1422cf4f7278aa1" }
]


[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"